source = ~/.config/hypr/myKeybinds.conf
source = ~/.config/hypr/myLook.conf


### VARIABLES ##
$fileManager = dolphin


### ENVIRONMENT VARIABLES ###
env = HYPRSHOT_DIR,$HOME/Pictures/screenshots
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24


### MONITORES ###
monitor=,preferred,1920x1080@144,1


exec-once = awww-daemon 
exec-once = awww img ~/Pictures/wallpapers/current_wp/current.png
exec-once = waybar & hyprlock & keyd-application-mapper 
exec-once = echo ~/.cache/wal/colors-waybar.css | /usr/bin/entr -r swayosd-server


### INPUT ###
input {
    kb_layout = es 
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =
    follow_mouse = 1

    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.
    touchpad {
        natural_scroll = true
	scroll_factor = 0.2
	tap-and-drag = false
    }
}

# https://wiki.hyprland.org/Configuring/Variables/#gestures
gesture = 3, horizontal, workspace

# Example per-device config
# See https://wiki.hyprland.org/Configuring/Keywords/#per-device-input-configs for more
device {
    name = epic-mouse-v1
    sensitivity = -0.5
}




